# Called via: cmake -DSRC_DIR=... -DBIN_DIR=... -DAPP_MAJOR=... -DAPP_MINOR=... -P increment_build.cmake
# Reads build_number.txt (major / minor / build, one per line).
# Resets build counter to 0 when major or minor changes, then increments by 1.
# Writes build/config/build_info.h into BIN_DIR/config/.

set(STATE_FILE "${SRC_DIR}/build_number.txt")

if(EXISTS "${STATE_FILE}")
    file(READ "${STATE_FILE}" _content)
    string(REPLACE "\n" ";" _lines "${_content}")
    list(GET _lines 0 _stored_major)
    list(GET _lines 1 _stored_minor)
    list(GET _lines 2 _stored_build)
    string(STRIP "${_stored_major}" _stored_major)
    string(STRIP "${_stored_minor}" _stored_minor)
    string(STRIP "${_stored_build}" _stored_build)
    if(NOT _stored_build MATCHES "^[0-9]+$")
        set(_stored_build 0)
    endif()
else()
    set(_stored_major "")
    set(_stored_minor "")
    set(_stored_build 0)
endif()

if(NOT "${_stored_major}" STREQUAL "${APP_MAJOR}" OR
   NOT "${_stored_minor}" STREQUAL "${APP_MINOR}")
    set(_build 0)
else()
    set(_build "${_stored_build}")
endif()

math(EXPR _build "${_build} + 1")

file(WRITE "${STATE_FILE}" "${APP_MAJOR}\n${APP_MINOR}\n${_build}\n")

set(_ver "${APP_MAJOR}.${APP_MINOR}.${_build}")

file(WRITE "${BIN_DIR}/config/build_info.h"
    "#pragma once\n"
    "/* Auto-generated by cmake/increment_build.cmake — do not edit */\n"
    "#define APP_VERSION_MAJOR ${APP_MAJOR}\n"
    "#define APP_VERSION_MINOR ${APP_MINOR}\n"
    "#define APP_BUILD_NUMBER  ${_build}\n"
    "#define APP_VERSION_STR   \"${_ver}\"\n"
)

file(WRITE "${BIN_DIR}/${PROJECT_NAME}.json"
    "{\"version\":\"${_ver}\"}\n"
)